#!/bin/sh
python inserter.py AL_Analysis_all.csv used_results AL_insert.sqlite
python inserter.py AR_Analysis_all.csv used_results AR_insert.sqlite
python inserter.py AZ_Analysis_all.csv used_results AZ_insert.sqlite
python inserter.py IL_Analysis_all.csv used_results CO_insert.sqlite
python inserter.py FL_Analysis_all.csv used_results FL_insert.sqlite
python inserter.py GA_Analysis_all.csv used_results GA_insert.sqlite
python inserter.py IA_Analysis_all.csv used_results IA_insert.sqlite
python inserter.py ID_Analysis_all.csv used_results ID_insert.sqlite
python inserter.py IL_Analysis_all.csv used_results IL_insert.sqlite
python inserter.py IL_Analysis_all.csv used_results KY_insert.sqlite
python inserter.py LA_Analysis_all.csv used_results LA_insert.sqlite
python inserter.py MA_Analysis_all.csv used_results MA_insert.sqlite
python inserter.py ME_Analysis_all.csv used_results ME_insert.sqlite
python inserter.py MI_Analysis_all.csv used_results MI_insert.sqlite
python inserter.py MO_Analysis_all.csv used_results MO_insert.sqlite
python inserter.py MS_Analysis_all.csv used_results MS_insert.sqlite
python inserter.py NC_Analysis_all.csv used_results NC_insert.sqlite
python inserter.py IL_Analysis_all.csv used_results NE_insert.sqlite
python inserter.py NH_Analysis_all.csv used_results NH_insert.sqlite
python inserter.py NV_Analysis_all.csv used_results NV_insert.sqlite
python inserter.py OH_Analysis_all.csv used_results OH_insert.sqlite
python inserter.py OK_Analysis_all.csv used_results OK_insert.sqlite
python inserter.py SC_Analysis_all.csv used_results SC_insert.sqlite
python inserter.py TN_Analysis_all.csv used_results TN_insert.sqlite
python inserter.py TX_Analysis_all.csv used_results TX_insert.sqlite
python inserter.py UT_Analysis_all.csv used_results UT_insert.sqlite
python inserter.py VA_Analysis_all.csv used_results VA_insert.sqlite
python inserter.py VT_Analysis_all.csv used_results VT_insert.sqlite
python inserter.py AL_Analysis_all.csv used_results AL_insert.sqlite